### ISSUE TITLE
Module crashes in production

### ISSUE THREAD

**Issue by barmac** [camunda/execution-platform#4]
Result after clicking on the create C7/C8 DMN button from welcome tab:

![Screen Shot 2022-03-31 at 18 16 54](https://user-images.githubusercontent.com/938244/161102279-2f1e0413-2965-4974-bd88-d1a57cd89d38.png)

Log message

```
[diagram_1.dmn] No provider for "e"! (Resolving: executionPlatform -> updateExecutionPlatformCommand -> e)
    at a (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:112:11)
    at error (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:98:14)
    at get (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:152:18)
    at file:///Applications/Camunda%20Modeler%20DMN%20Version%20Select.app/Contents/Resources/app.asar/public/3.3.js:1:38603
    at Array.map (<anonymous>)
    at map (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:170:30)
    at fnDef (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:185:14)
    at providers (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:146:43)
    at file:///Applications/Camunda%20Modeler%20DMN%20Version%20Select.app/Contents/Resources/app.asar/public/3.3.js:1:56365
    at Array.forEach (<anonymous>) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler/pull/2877#) [ info ]
[diagram_1.dmn] No provider for "e"! (Resolving: executionPlatform -> updateExecutionPlatformCommand -> e)
    at a (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:112:11)
    at error (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:98:14)
    at get (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:152:18)
    at file:///Applications/Camunda%20Modeler%20DMN%20Version%20Select.app/Contents/Resources/app.asar/public/3.3.js:1:38603
    at Array.map (<anonymous>)
    at map (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:170:30)
    at fnDef (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:185:14)
    at providers (webpack:///node_modules/diagram-js/node_modules/didi/dist/index.esm.js:146:43)
    at file:///Applications/Camunda%20Modeler%20DMN%20Version%20Select.app/Contents/Resources/app.asar/public/3.3.js:1:56365
    at Array.forEach (<anonymous>) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler/pull/2877#) [ info ]

```

_Originally posted by @andreasgeier in https://github.com/camunda/camunda-modeler/issues/2877#issuecomment-1084805262_

**Comment by barmac** [comment]
This is still not fixed in v0.3.1.
